version: "3"

services:
  app:
    image: yolov8-gpu
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: prod
      args:
        PYPROJECT_FILE: ./requirements/gpu/pyproject.toml
    volumes:
      - ./ui:/home/ai/ui
      - ./ui:/home/ui
    ports:
      - 8010:8000
    container_name: yolov8-gpu
